"""Monte Carlo trade-sequence resampling (Phase 3 Epic E3.3), per
Phase_6_Trading_Engine_Design.md §3:

  "Process: The trade sequence generated by the backtest is randomized and resampled 10,000
  times. Validation: This simulates extreme market events and bad luck. The 95th percentile
  Max Drawdown from the Monte Carlo simulation is used as the absolute risk metric, not the
  historical Max Drawdown."

A backtest only realizes one particular ORDER in which a strategy's trades happened to occur.
Shuffling that same set of trade returns into many different orders (bootstrap resampling with
replacement, per-path) reveals how much worse the equity curve's drawdown could plausibly have
been purely from bad luck in trade sequencing -- e.g. several losing trades clustering together
early, before the strategy has built up a cash buffer. The historical Max Drawdown is just one
sample from that distribution; the 95th percentile is the risk figure actually used downstream
(Kill Switch threshold comparisons, Evaluator Agent gating).
"""

from dataclasses import dataclass

import numpy as np

DEFAULT_N_SIMULATIONS = 10_000
DRAWDOWN_PERCENTILE = 95.0


@dataclass(frozen=True)
class MonteCarloResult:
    n_simulations: int
    historical_max_drawdown: float
    simulated_max_drawdowns: np.ndarray
    percentile_95_max_drawdown: float

    @property
    def is_worse_than_historical(self) -> bool:
        """The whole point of the exercise: the 95th-percentile simulated Max DD should govern
        risk decisions instead of the historical Max DD, precisely because it's typically worse
        (a strategy that got a lucky trade ordering historically doesn't get the benefit of that
        luck across all 10,000 resampled paths)."""
        return self.percentile_95_max_drawdown >= self.historical_max_drawdown


def max_drawdown_from_returns(trade_returns: np.ndarray) -> float:
    """Max Drawdown (positive fraction) of the equity curve built by compounding a sequence of
    per-trade returns starting from an equity of 1.0 -- same sign convention as
    src/engine/backtest/metrics.py's BacktestMetrics.max_drawdown.

    The starting equity of 1.0 is prepended explicitly, not just implied by the first trade's
    return: otherwise a loss on the very first trade would never register as a drawdown at all
    (the running peak would "catch up" to the reduced value immediately, since there's no
    earlier, higher point in the array to measure the decline against)."""
    if len(trade_returns) == 0:
        return 0.0
    equity_curve = np.concatenate(([1.0], np.cumprod(1.0 + trade_returns)))
    running_peak = np.maximum.accumulate(equity_curve)
    drawdowns = (running_peak - equity_curve) / running_peak
    return float(drawdowns.max())


def run_monte_carlo_simulation(
    trade_returns: list[float],
    *,
    n_simulations: int = DEFAULT_N_SIMULATIONS,
    seed: int | None = None,
) -> MonteCarloResult:
    """Resamples `trade_returns` (fractional per-trade returns from a completed backtest, in
    their original order for the historical baseline) `n_simulations` times with replacement,
    computing the Max Drawdown of each resampled equity curve, and returns the 95th percentile
    across all simulated paths as the governing risk metric."""
    if not trade_returns:
        return MonteCarloResult(
            n_simulations=n_simulations,
            historical_max_drawdown=0.0,
            simulated_max_drawdowns=np.array([]),
            percentile_95_max_drawdown=0.0,
        )

    returns = np.asarray(trade_returns, dtype=float)
    historical_max_drawdown = max_drawdown_from_returns(returns)

    rng = np.random.default_rng(seed)
    simulated_max_drawdowns = np.empty(n_simulations)
    for i in range(n_simulations):
        resampled = rng.choice(returns, size=len(returns), replace=True)
        simulated_max_drawdowns[i] = max_drawdown_from_returns(resampled)

    percentile_95 = float(np.percentile(simulated_max_drawdowns, DRAWDOWN_PERCENTILE))

    return MonteCarloResult(
        n_simulations=n_simulations,
        historical_max_drawdown=historical_max_drawdown,
        simulated_max_drawdowns=simulated_max_drawdowns,
        percentile_95_max_drawdown=percentile_95,
    )
