apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-tradingos-api
spec:
  type: {{ .Values.service.type }}
  selector:
    app: tradingos-api
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
      protocol: TCP
